from base.exceptions import CommandError


class CustomerValidationError(CommandError):
    pass
